### ISSUE TITLE
Hide/Show Elements as You Scroll

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/responsive-infographic#1]
Hey @thomasjbradley

I was just wondering if you knew of a simple-ish way to reveal/hide elements as you scroll down a page. Sort of what I'm thinking is that elements wouldn't be visible, then as you scroll and they are come onto the page they would animate in (opacity to keep it REAL simple for me lol) and as you scroll past them they would be invisible again.

I assume for that part would be a simple add/remove classes but I'm struggling with the triggering it with the window/view.

Any insights would be awesome!
Thanks for letting us bug you about code 😄

**Comment by thomasjbradley** [comment]
Yep, it’s a simple as adding & removing elements.

Here’s a video: https://www.youtube.com/watch?v=5hPVpVtgle4

**Comment by JessJodoin** [comment]
Thank you so much!

I feel kinda dumb cause I've definitely watched this video before a few times lol my poor brain is empty 😭 

Anyways, thanks again and have a great rest of your week!
